version: '3.7'

services:
  main:
    container_name: NestJs
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: npm run start:dev